### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ghOvidiu** [ghOvidiu/marketing-hr-platform#3]
- [ ] User profile page
- [ ] Company profile page
- [ ] "Add a new job opening" page
- [ ] Filter box for jobs in "index.php" 
- [ ] Fetch job-posts from database
